/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './app/__root'
import { Route as mainLayoutRouteImport } from './app/(main)/layout'
import { Route as authLayoutRouteImport } from './app/(auth)/layout'
import { Route as maindashboardPageRouteImport } from './app/(main)/(dashboard)/page'

const mainProfilePageLazyRouteImport = createFileRoute('/(main)/profile/')()
const mainExpensePageLazyRouteImport = createFileRoute('/(main)/expense/')()
const authRegisterPageLazyRouteImport = createFileRoute('/(auth)/register/')()
const authLoginPageLazyRouteImport = createFileRoute('/(auth)/login/')()

const mainLayoutRoute = mainLayoutRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainProfilePageLazyRoute = mainProfilePageLazyRouteImport
  .update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => mainLayoutRoute,
  } as any)
  .lazy(() => import('./app/(main)/profile/page.lazy').then((d) => d.Route))
const mainExpensePageLazyRoute = mainExpensePageLazyRouteImport
  .update({
    id: '/expense/',
    path: '/expense/',
    getParentRoute: () => mainLayoutRoute,
  } as any)
  .lazy(() => import('./app/(main)/expense/page.lazy').then((d) => d.Route))
const authRegisterPageLazyRoute = authRegisterPageLazyRouteImport
  .update({
    id: '/register/',
    path: '/register/',
    getParentRoute: () => authLayoutRoute,
  } as any)
  .lazy(() => import('./app/(auth)/register/page.lazy').then((d) => d.Route))
const authLoginPageLazyRoute = authLoginPageLazyRouteImport
  .update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => authLayoutRoute,
  } as any)
  .lazy(() => import('./app/(auth)/login/page.lazy').then((d) => d.Route))
const maindashboardPageRoute = maindashboardPageRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof maindashboardPageRoute
  '/login/': typeof authLoginPageLazyRoute
  '/register/': typeof authRegisterPageLazyRoute
  '/expense/': typeof mainExpensePageLazyRoute
  '/profile/': typeof mainProfilePageLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof maindashboardPageRoute
  '/login': typeof authLoginPageLazyRoute
  '/register': typeof authRegisterPageLazyRoute
  '/expense': typeof mainExpensePageLazyRoute
  '/profile': typeof mainProfilePageLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(main)': typeof mainLayoutRouteWithChildren
  '/(main)/(dashboard)/': typeof maindashboardPageRoute
  '/(auth)/login/': typeof authLoginPageLazyRoute
  '/(auth)/register/': typeof authRegisterPageLazyRoute
  '/(main)/expense/': typeof mainExpensePageLazyRoute
  '/(main)/profile/': typeof mainProfilePageLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/register/' | '/expense/' | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/expense' | '/profile'
  id:
    | '__root__'
    | '/(auth)'
    | '/(main)'
    | '/(main)/(dashboard)/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(main)/expense/'
    | '/(main)/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/profile/': {
      id: '/(main)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof mainProfilePageLazyRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/expense/': {
      id: '/(main)/expense/'
      path: '/expense'
      fullPath: '/expense/'
      preLoaderRoute: typeof mainExpensePageLazyRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterPageLazyRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginPageLazyRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(main)/(dashboard)/': {
      id: '/(main)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof maindashboardPageRouteImport
      parentRoute: typeof mainLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLoginPageLazyRoute: typeof authLoginPageLazyRoute
  authRegisterPageLazyRoute: typeof authRegisterPageLazyRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLoginPageLazyRoute: authLoginPageLazyRoute,
  authRegisterPageLazyRoute: authRegisterPageLazyRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface mainLayoutRouteChildren {
  maindashboardPageRoute: typeof maindashboardPageRoute
  mainExpensePageLazyRoute: typeof mainExpensePageLazyRoute
  mainProfilePageLazyRoute: typeof mainProfilePageLazyRoute
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  maindashboardPageRoute: maindashboardPageRoute,
  mainExpensePageLazyRoute: mainExpensePageLazyRoute,
  mainProfilePageLazyRoute: mainProfilePageLazyRoute,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  mainLayoutRoute: mainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
